// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ConsumptionDataReportType.
const (
	ConsumptionDataReportTypeNetConsumption   ConsumptionDataReportType = "net-consumption"
	ConsumptionDataReportTypeTotalConsumption ConsumptionDataReportType = "total-consumption"
)

// Defines values for GridReadingChannelsPhase.
const (
	L1 GridReadingChannelsPhase = "L1"
	L2 GridReadingChannelsPhase = "L2"
	L3 GridReadingChannelsPhase = "L3"
)

// Defines values for MeterDetailsMeasurementType.
const (
	MeterDetailsMeasurementTypeNetConsumption MeterDetailsMeasurementType = "net-consumption"
	MeterDetailsMeasurementTypeProduction     MeterDetailsMeasurementType = "production"
	MeterDetailsMeasurementTypeStorage        MeterDetailsMeasurementType = "storage"
)

// ConsumptionData Power consumption information
type ConsumptionData struct {
	// CreatedAt Epoch timestamp of measurement
	CreatedAt *int64 `json:"createdAt,omitempty"`

	// Cumulative Cumulative results of all phases
	Cumulative *struct {
		// ActPower Active power (Watts)
		ActPower *float32 `json:"actPower,omitempty"`

		// ApprntPwr Apparent power (VA)
		ApprntPwr *float32 `json:"apprntPwr,omitempty"`

		// CurrW Instantaneous active power (Watts)
		CurrW *float32 `json:"currW,omitempty"`

		// FreqHz Frequency (Hz)
		FreqHz *float32 `json:"freqHz,omitempty"`

		// PwrFactor Power factor
		PwrFactor *float32 `json:"pwrFactor,omitempty"`

		// ReactPwr Reactive power (VAr)
		ReactPwr *float32 `json:"reactPwr,omitempty"`

		// RmsCurrent RMS current (Amperes)
		RmsCurrent *float32 `json:"rmsCurrent,omitempty"`

		// RmsVoltage RMS voltage (Volts)
		RmsVoltage *float32 `json:"rmsVoltage,omitempty"`

		// VahCum Cumulative apparent energy (VAh)
		VahCum *float32 `json:"vahCum,omitempty"`

		// VarhLagCum Cumulative lagging reactive energy (VArh)
		VarhLagCum *float32 `json:"varhLagCum,omitempty"`

		// VarhLeadCum Cumulative leading reactive energy (VArh)
		VarhLeadCum *float32 `json:"varhLeadCum,omitempty"`

		// WhDlvdCum Cumulative active energy delivered (Wh)
		WhDlvdCum *float32 `json:"whDlvdCum,omitempty"`

		// WhRcvdCum Cumulative active energy received (Wh)
		WhRcvdCum *float32 `json:"whRcvdCum,omitempty"`
	} `json:"cumulative,omitempty"`

	// Lines Per-phase measurements
	Lines *[]struct {
		// ActPower Active power (Watts)
		ActPower *float32 `json:"actPower,omitempty"`

		// ApprntPwr Apparent power (VA)
		ApprntPwr *float32 `json:"apprntPwr,omitempty"`

		// CurrW Instantaneous active power (Watts)
		CurrW *float32 `json:"currW,omitempty"`

		// FreqHz Frequency (Hz)
		FreqHz *float32 `json:"freqHz,omitempty"`

		// PwrFactor Power factor
		PwrFactor *float32 `json:"pwrFactor,omitempty"`

		// ReactPwr Reactive power (VAr)
		ReactPwr *float32 `json:"reactPwr,omitempty"`

		// RmsCurrent RMS current (Amperes)
		RmsCurrent *float32 `json:"rmsCurrent,omitempty"`

		// RmsVoltage RMS voltage (Volts)
		RmsVoltage *float32 `json:"rmsVoltage,omitempty"`

		// VahCum Cumulative apparent energy (VAh)
		VahCum *float32 `json:"vahCum,omitempty"`

		// VarhLagCum Cumulative lagging reactive energy (VArh)
		VarhLagCum *float32 `json:"varhLagCum,omitempty"`

		// VarhLeadCum Cumulative leading reactive energy (VArh)
		VarhLeadCum *float32 `json:"varhLeadCum,omitempty"`

		// WhDlvdCum Cumulative active energy delivered (Wh)
		WhDlvdCum *float32 `json:"whDlvdCum,omitempty"`

		// WhRcvdCum Cumulative active energy received (Wh)
		WhRcvdCum *float32 `json:"whRcvdCum,omitempty"`
	} `json:"lines,omitempty"`

	// ReportType Type of consumption report
	ReportType *ConsumptionDataReportType `json:"reportType,omitempty"`
}

// ConsumptionDataReportType Type of consumption report
type ConsumptionDataReportType string

// DeviceList List of provisioned devices and their commissioning status
type DeviceList struct {
	// Devices Array of provisioned devices
	Devices *[]struct {
		// ComInterface Communication interface
		ComInterface *int `json:"com_interface,omitempty"`

		// ComInterfaceStr Communication interface string
		ComInterfaceStr *string `json:"com_interface_str,omitempty"`
		DevInfo         *struct {
			// DERIndex Connected phase (1=Phase1, 2=Phase2, 3=Phase3)
			DERIndex *int `json:"DER_Index,omitempty"`

			// Capacity Device capacity in watt-hours
			Capacity *int `json:"capacity,omitempty"`
		} `json:"dev_info,omitempty"`

		// DeviceType Device type (0=Unknown, 13=Storage, 14=Microinverters)
		DeviceType *int `json:"device_type,omitempty"`

		// SerialNumber Serial number of the device
		SerialNumber *string `json:"serial_number,omitempty"`

		// Status Device connection status
		Status *string `json:"status,omitempty"`
	} `json:"devices,omitempty"`
	Usb *struct {
		// AutoScan Auto scan status
		AutoScan *string `json:"auto_scan,omitempty"`

		// Ck2Bridge CK2 bridge connection status
		Ck2Bridge *string `json:"ck2_bridge,omitempty"`
	} `json:"usb,omitempty"`
}

// EnergyData Energy data for microinverters, meters, production and consumption
type EnergyData struct {
	Consumption *struct {
		// Eim Envoy Internal consumption meter
		Eim *struct {
			// WattHoursLifetime Total energy lifetime (Wh)
			WattHoursLifetime *int `json:"wattHoursLifetime,omitempty"`

			// WattHoursSevenDays Total energy last 7 days (Wh)
			WattHoursSevenDays *int `json:"wattHoursSevenDays,omitempty"`

			// WattHoursToday Total energy today (Wh)
			WattHoursToday *int `json:"wattHoursToday,omitempty"`

			// WattsNow Current active power (Watts)
			WattsNow *int `json:"wattsNow,omitempty"`
		} `json:"eim,omitempty"`
	} `json:"consumption,omitempty"`
	Production *struct {
		// Eim Envoy Internal production meter
		Eim *struct {
			// WattHoursLifetime Total energy lifetime (Wh)
			WattHoursLifetime *int `json:"wattHoursLifetime,omitempty"`

			// WattHoursSevenDays Total energy last 7 days (Wh)
			WattHoursSevenDays *int `json:"wattHoursSevenDays,omitempty"`

			// WattHoursToday Total energy today (Wh)
			WattHoursToday *int `json:"wattHoursToday,omitempty"`

			// WattsNow Current active power (Watts)
			WattsNow *int `json:"wattsNow,omitempty"`
		} `json:"eim,omitempty"`

		// Pcu Measurements from microinverters
		Pcu *struct {
			// WattHoursLifetime Total energy lifetime (Wh)
			WattHoursLifetime *int `json:"wattHoursLifetime,omitempty"`

			// WattHoursSevenDays Total energy last 7 days (Wh)
			WattHoursSevenDays *int `json:"wattHoursSevenDays,omitempty"`

			// WattHoursToday Total energy today (Wh)
			WattHoursToday *int `json:"wattHoursToday,omitempty"`

			// WattsNow Current active power (Watts)
			WattsNow *int `json:"wattsNow,omitempty"`
		} `json:"pcu,omitempty"`

		// Rgm Revenue grade meter (not applicable)
		Rgm *struct {
			WattHoursLifetime  *int `json:"wattHoursLifetime,omitempty"`
			WattHoursSevenDays *int `json:"wattHoursSevenDays,omitempty"`
			WattHoursToday     *int `json:"wattHoursToday,omitempty"`
			WattsNow           *int `json:"wattsNow,omitempty"`
		} `json:"rgm,omitempty"`
	} `json:"production,omitempty"`
}

// Error Error response
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Error message
	Error *string `json:"error,omitempty"`
}

// GridReading Grid connection voltage, current, frequency, and power readings
type GridReading = []struct {
	// Channels Per-phase grid readings
	Channels *[]struct {
		// ActivePower Instantaneous active power (Watts, negative=export)
		ActivePower *float32 `json:"activePower,omitempty"`

		// Current Measured current (Amperes)
		Current *float32 `json:"current,omitempty"`

		// Freq Measured frequency (Hz)
		Freq *float32 `json:"freq,omitempty"`

		// Phase Phase identifier
		Phase *GridReadingChannelsPhase `json:"phase,omitempty"`

		// ReactivePower Instantaneous reactive power (VAr)
		ReactivePower *float32 `json:"reactivePower,omitempty"`

		// Voltage Measured voltage (Volts)
		Voltage *float32 `json:"voltage,omitempty"`
	} `json:"channels,omitempty"`
}

// GridReadingChannelsPhase Phase identifier
type GridReadingChannelsPhase string

// InverterProduction Microinverter production information
type InverterProduction = []struct {
	// DevType Device type
	DevType *int `json:"devType,omitempty"`

	// LastReportDate Last report time in epoch format
	LastReportDate *int64 `json:"lastReportDate,omitempty"`

	// LastReportWatts Last reported active power (Watts)
	LastReportWatts *int `json:"lastReportWatts,omitempty"`

	// MaxReportWatts Maximum ever reported power (Watts)
	MaxReportWatts *int `json:"maxReportWatts,omitempty"`

	// SerialNumber Serial number of microinverter
	SerialNumber *string `json:"serialNumber,omitempty"`
}

// LiveDataStatus Meter live data with tasks and counters
type LiveDataStatus struct {
	Connection *struct {
		// AuthState Authentication status
		AuthState *string `json:"auth_state,omitempty"`

		// MqttState MQTT broker status
		MqttState *string `json:"mqtt_state,omitempty"`

		// ProvState Provisioning status
		ProvState *string `json:"prov_state,omitempty"`

		// ScDebug Status of debug stream
		ScDebug *string `json:"sc_debug,omitempty"`

		// ScStream Status of live data stream
		ScStream *string `json:"sc_stream,omitempty"`
	} `json:"connection,omitempty"`

	// Counters Various system counters
	Counters *map[string]int `json:"counters,omitempty"`
	Meters   *struct {
		// AcbAggEnergy Aggregate energy of AC battery (Wh)
		AcbAggEnergy *int `json:"acb_agg_energy,omitempty"`

		// AcbAggSoc Aggregate SoC of AC battery (%)
		AcbAggSoc *int `json:"acb_agg_soc,omitempty"`

		// BackupBatMode Backup battery mode
		BackupBatMode *int `json:"backup_bat_mode,omitempty"`

		// BackupSoc Backup battery state of charge (%)
		BackupSoc *int `json:"backup_soc,omitempty"`

		// EncAggEnergy Aggregate energy of Encharge (Wh)
		EncAggEnergy *int `json:"enc_agg_energy,omitempty"`

		// EncAggSoc Aggregate SoC of Encharge (%)
		EncAggSoc *int `json:"enc_agg_soc,omitempty"`

		// GenRelayState Generator relay state
		GenRelayState *int `json:"gen_relay_state,omitempty"`

		// Generator Generator meter readings
		Generator *struct {
			// AggPMw Aggregate active power (milliwatts)
			AggPMw *int `json:"agg_p_mw,omitempty"`

			// AggPPhAMw Aggregate active power phase A (milliwatts)
			AggPPhAMw *int `json:"agg_p_ph_a_mw,omitempty"`

			// AggPPhBMw Aggregate active power phase B (milliwatts)
			AggPPhBMw *int `json:"agg_p_ph_b_mw,omitempty"`

			// AggPPhCMw Aggregate active power phase C (milliwatts)
			AggPPhCMw *int `json:"agg_p_ph_c_mw,omitempty"`

			// AggSMva Aggregate apparent power (milli volt-amperes)
			AggSMva *int `json:"agg_s_mva,omitempty"`

			// AggSPhAMva Aggregate apparent power phase A (milli volt-amperes)
			AggSPhAMva *int `json:"agg_s_ph_a_mva,omitempty"`

			// AggSPhBMva Aggregate apparent power phase B (milli volt-amperes)
			AggSPhBMva *int `json:"agg_s_ph_b_mva,omitempty"`

			// AggSPhCMva Aggregate apparent power phase C (milli volt-amperes)
			AggSPhCMva *int `json:"agg_s_ph_c_mva,omitempty"`
		} `json:"generator,omitempty"`

		// Grid Grid meter readings
		Grid *struct {
			// AggPMw Aggregate active power (milliwatts)
			AggPMw *int `json:"agg_p_mw,omitempty"`

			// AggPPhAMw Aggregate active power phase A (milliwatts)
			AggPPhAMw *int `json:"agg_p_ph_a_mw,omitempty"`

			// AggPPhBMw Aggregate active power phase B (milliwatts)
			AggPPhBMw *int `json:"agg_p_ph_b_mw,omitempty"`

			// AggPPhCMw Aggregate active power phase C (milliwatts)
			AggPPhCMw *int `json:"agg_p_ph_c_mw,omitempty"`

			// AggSMva Aggregate apparent power (milli volt-amperes)
			AggSMva *int `json:"agg_s_mva,omitempty"`

			// AggSPhAMva Aggregate apparent power phase A (milli volt-amperes)
			AggSPhAMva *int `json:"agg_s_ph_a_mva,omitempty"`

			// AggSPhBMva Aggregate apparent power phase B (milli volt-amperes)
			AggSPhBMva *int `json:"agg_s_ph_b_mva,omitempty"`

			// AggSPhCMva Aggregate apparent power phase C (milli volt-amperes)
			AggSPhCMva *int `json:"agg_s_ph_c_mva,omitempty"`
		} `json:"grid,omitempty"`

		// IsSplitPhase Split-phase grid type indicator
		IsSplitPhase *int `json:"is_split_phase,omitempty"`

		// LastUpdate Last meter data collection timestamp
		LastUpdate *int64 `json:"last_update,omitempty"`

		// Load Load meter readings
		Load *struct {
			// AggPMw Aggregate active power (milliwatts)
			AggPMw *int `json:"agg_p_mw,omitempty"`

			// AggPPhAMw Aggregate active power phase A (milliwatts)
			AggPPhAMw *int `json:"agg_p_ph_a_mw,omitempty"`

			// AggPPhBMw Aggregate active power phase B (milliwatts)
			AggPPhBMw *int `json:"agg_p_ph_b_mw,omitempty"`

			// AggPPhCMw Aggregate active power phase C (milliwatts)
			AggPPhCMw *int `json:"agg_p_ph_c_mw,omitempty"`

			// AggSMva Aggregate apparent power (milli volt-amperes)
			AggSMva *int `json:"agg_s_mva,omitempty"`

			// AggSPhAMva Aggregate apparent power phase A (milli volt-amperes)
			AggSPhAMva *int `json:"agg_s_ph_a_mva,omitempty"`

			// AggSPhBMva Aggregate apparent power phase B (milli volt-amperes)
			AggSPhBMva *int `json:"agg_s_ph_b_mva,omitempty"`

			// AggSPhCMva Aggregate apparent power phase C (milli volt-amperes)
			AggSPhCMva *int `json:"agg_s_ph_c_mva,omitempty"`
		} `json:"load,omitempty"`

		// MainRelayState Main relay state
		MainRelayState *int `json:"main_relay_state,omitempty"`

		// PhaseCount Number of connected phases
		PhaseCount *int `json:"phase_count,omitempty"`

		// Pv Photovoltaic meter readings
		Pv *struct {
			// AggPMw Aggregate active power (milliwatts)
			AggPMw *int `json:"agg_p_mw,omitempty"`

			// AggPPhAMw Aggregate active power phase A (milliwatts)
			AggPPhAMw *int `json:"agg_p_ph_a_mw,omitempty"`

			// AggPPhBMw Aggregate active power phase B (milliwatts)
			AggPPhBMw *int `json:"agg_p_ph_b_mw,omitempty"`

			// AggPPhCMw Aggregate active power phase C (milliwatts)
			AggPPhCMw *int `json:"agg_p_ph_c_mw,omitempty"`

			// AggSMva Aggregate apparent power (milli volt-amperes)
			AggSMva *int `json:"agg_s_mva,omitempty"`

			// AggSPhAMva Aggregate apparent power phase A (milli volt-amperes)
			AggSPhAMva *int `json:"agg_s_ph_a_mva,omitempty"`

			// AggSPhBMva Aggregate apparent power phase B (milli volt-amperes)
			AggSPhBMva *int `json:"agg_s_ph_b_mva,omitempty"`

			// AggSPhCMva Aggregate apparent power phase C (milli volt-amperes)
			AggSPhCMva *int `json:"agg_s_ph_c_mva,omitempty"`
		} `json:"pv,omitempty"`

		// Soc State of charge of storage device (%)
		Soc *int `json:"soc,omitempty"`

		// Storage Battery storage meter readings
		Storage *struct {
			// AggPMw Aggregate active power (milliwatts)
			AggPMw *int `json:"agg_p_mw,omitempty"`

			// AggPPhAMw Aggregate active power phase A (milliwatts)
			AggPPhAMw *int `json:"agg_p_ph_a_mw,omitempty"`

			// AggPPhBMw Aggregate active power phase B (milliwatts)
			AggPPhBMw *int `json:"agg_p_ph_b_mw,omitempty"`

			// AggPPhCMw Aggregate active power phase C (milliwatts)
			AggPPhCMw *int `json:"agg_p_ph_c_mw,omitempty"`

			// AggSMva Aggregate apparent power (milli volt-amperes)
			AggSMva *int `json:"agg_s_mva,omitempty"`

			// AggSPhAMva Aggregate apparent power phase A (milli volt-amperes)
			AggSPhAMva *int `json:"agg_s_ph_a_mva,omitempty"`

			// AggSPhBMva Aggregate apparent power phase B (milli volt-amperes)
			AggSPhBMva *int `json:"agg_s_ph_b_mva,omitempty"`

			// AggSPhCMva Aggregate apparent power phase C (milli volt-amperes)
			AggSPhCMva *int `json:"agg_s_ph_c_mva,omitempty"`
		} `json:"storage,omitempty"`
	} `json:"meters,omitempty"`
	Tasks *struct {
		// TaskId ID of most recent task processed
		TaskId *int `json:"task_id,omitempty"`

		// Timestamp Unix timestamp of last task processed
		Timestamp *int64 `json:"timestamp,omitempty"`
	} `json:"tasks,omitempty"`
}

// MeterDetails Meter status, type, and phase information
type MeterDetails = []struct {
	// Eid Meter ID
	Eid *int64 `json:"eid,omitempty"`

	// MeasurementType Type of measurement
	MeasurementType *MeterDetailsMeasurementType `json:"measurementType,omitempty"`

	// MeteringStatus Metering status
	MeteringStatus *string `json:"meteringStatus,omitempty"`

	// PhaseCount Number of phases meter is monitoring
	PhaseCount *int `json:"phaseCount,omitempty"`

	// PhaseMode Number of phases the meter hardware can monitor
	PhaseMode *string `json:"phaseMode,omitempty"`

	// State Meter state (enabled/disabled)
	State *string `json:"state,omitempty"`

	// StatusFlags Status flags
	StatusFlags *[]string `json:"statusFlags,omitempty"`
}

// MeterDetailsMeasurementType Type of measurement
type MeterDetailsMeasurementType string

// MeterReadings Measurements from production, storage, and consumption CTs
type MeterReadings = []struct {
	// ActEnergyDlvd Overall active energy delivered (Wh)
	ActEnergyDlvd *float32 `json:"actEnergyDlvd,omitempty"`

	// ActEnergyRcvd Overall active energy received (Wh)
	ActEnergyRcvd *float32 `json:"actEnergyRcvd,omitempty"`

	// ActivePower Instantaneous active power (Watts)
	ActivePower *float32 `json:"activePower,omitempty"`

	// ApparentEnergy Overall apparent energy (VAh)
	ApparentEnergy *float32 `json:"apparentEnergy,omitempty"`

	// ApparentPower Instantaneous apparent power (VA)
	ApparentPower *float32 `json:"apparentPower,omitempty"`

	// Channels Per-phase channel measurements
	Channels *[]struct {
		// ActEnergyDlvd Active energy delivered in this channel (Wh)
		ActEnergyDlvd *float32 `json:"actEnergyDlvd,omitempty"`

		// ActEnergyRcvd Active energy received in this channel (Wh)
		ActEnergyRcvd *float32 `json:"actEnergyRcvd,omitempty"`

		// ActivePower Instantaneous active power in this channel (Watts)
		ActivePower *float32 `json:"activePower,omitempty"`

		// ApparentEnergy Apparent energy in this channel (VAh)
		ApparentEnergy *float32 `json:"apparentEnergy,omitempty"`

		// ApparentPower Instantaneous apparent power in this channel (VA)
		ApparentPower *float32 `json:"apparentPower,omitempty"`

		// Current Measured current in this channel (Amperes)
		Current *float32 `json:"current,omitempty"`

		// Eid Channel ID
		Eid *int64 `json:"eid,omitempty"`

		// Freq Measured frequency in this channel (Hz)
		Freq *float32 `json:"freq,omitempty"`

		// InstantaneousDemand Instantaneous active power demand in this channel (Watts)
		InstantaneousDemand *float32 `json:"instantaneousDemand,omitempty"`

		// PwrFactor Measured power factor in this channel
		PwrFactor *float32 `json:"pwrFactor,omitempty"`

		// ReactEnergyLagg Lagging reactive energy in this channel (VArh)
		ReactEnergyLagg *float32 `json:"reactEnergyLagg,omitempty"`

		// ReactEnergyLead Leading reactive energy in this channel (VArh)
		ReactEnergyLead *float32 `json:"reactEnergyLead,omitempty"`

		// ReactivePower Instantaneous reactive power in this channel (VAr)
		ReactivePower *float32 `json:"reactivePower,omitempty"`

		// Timestamp Epoch timestamp
		Timestamp *int64 `json:"timestamp,omitempty"`

		// Voltage Measured voltage in this channel (Volts)
		Voltage *float32 `json:"voltage,omitempty"`
	} `json:"channels,omitempty"`

	// Current Measured current (Amperes)
	Current *float32 `json:"current,omitempty"`

	// Eid Meter ID
	Eid *int64 `json:"eid,omitempty"`

	// Freq Measured frequency (Hz)
	Freq *float32 `json:"freq,omitempty"`

	// InstantaneousDemand Instantaneous active power demand (Watts)
	InstantaneousDemand *float32 `json:"instantaneousDemand,omitempty"`

	// PwrFactor Measured power factor
	PwrFactor *float32 `json:"pwrFactor,omitempty"`

	// ReactEnergyLagg Overall lagging reactive energy (VArh)
	ReactEnergyLagg *float32 `json:"reactEnergyLagg,omitempty"`

	// ReactEnergyLead Overall leading reactive energy (VArh)
	ReactEnergyLead *float32 `json:"reactEnergyLead,omitempty"`

	// ReactivePower Instantaneous reactive power (VAr)
	ReactivePower *float32 `json:"reactivePower,omitempty"`

	// Timestamp Epoch timestamp of measurement
	Timestamp *int64 `json:"timestamp,omitempty"`

	// Voltage Measured voltage (Volts)
	Voltage *float32 `json:"voltage,omitempty"`
}

// ProductionData Production energy and power values
type ProductionData struct {
	// WattHoursLifetime Total energy produced lifetime (Wh)
	WattHoursLifetime *int `json:"wattHoursLifetime,omitempty"`

	// WattHoursSevenDays Total energy produced in last 7 days (Wh)
	WattHoursSevenDays *int `json:"wattHoursSevenDays,omitempty"`

	// WattHoursToday Total energy produced today (Wh)
	WattHoursToday *int `json:"wattHoursToday,omitempty"`

	// WattsNow Current active power production (Watts)
	WattsNow *int `json:"wattsNow,omitempty"`
}

// SystemInfo System information including serial number, model, and firmware versions
type SystemInfo struct {
	Device *struct {
		// Apiver API version
		Apiver *int `json:"apiver,omitempty"`

		// Euaid Gateway EUAID
		Euaid *string `json:"euaid,omitempty"`

		// Imeter Internal meter presence
		Imeter *bool `json:"imeter,omitempty"`

		// Pn Gateway part number
		Pn *string `json:"pn,omitempty"`

		// Seqnum Sequence number
		Seqnum *int `json:"seqnum,omitempty"`

		// Sn Gateway serial number
		Sn *string `json:"sn,omitempty"`

		// Software Gateway software version
		Software *string `json:"software,omitempty"`
	} `json:"device,omitempty"`

	// Packages Installed software packages
	Packages *[]struct {
		// Build Build identifier
		Build *string `json:"build,omitempty"`

		// Name Package name
		Name *string `json:"name,omitempty"`

		// Pn Part number
		Pn *string `json:"pn,omitempty"`

		// Version Package version
		Version *string `json:"version,omitempty"`
	} `json:"packages,omitempty"`

	// Time Unix timestamp
	Time *int64 `json:"time,omitempty"`

	// WebTokens Web tokens support
	WebTokens *bool `json:"web-tokens,omitempty"`
}
